# Generated by Django 4.1.3 on 2022-11-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('сompany_name', models.CharField(max_length=210)),
                ('founder', models.CharField(max_length=210)),
                ('email', models.CharField(max_length=210)),
                ('additional_information', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('model', models.CharField(max_length=210)),
                ('brand', models.CharField(max_length=210)),
                ('provider', models.CharField(max_length=210)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('characteristic', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercedes.provider')),
            ],
        ),
    ]
